### ISSUE TITLE
How do I get the UUID?

### ISSUE THREAD

**Issue by kunalkhosla** [bvlaicu/coned#5]
Been trying to find a good way to fine the UUID for oru.

Looking at network tab and such places but can't find a good way. Tried a few which looked like a UUID, but no bueno.
Any ideas how I can get the UUID?

**Comment by varenc** [comment]
how'd you find it? having the same challenge

**Comment by kunalkhosla** [comment]
I updated some instructions on https://github.com/bvlaicu/home-assistant-addons/blob/master/oru/README.md#option-account_uuid

See if that helps
